service: geotiff-server

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-southeast-2

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:GetObject"
     Resource:
       - "arn:aws:s3:::dea-public-data/*"

custom:
  apigwBinary:
    types:
      - '*/*'

plugins:
  - serverless-apigw-binary

package:
  individually: true
  exclude:
    - ./**

functions:
  app:
    handler: server.handler
    memorySize: 1536
    timeout: 20
    events:
      - http:
          path: /{any+}
          method: get
          cors: true
    environment:
      NODE_ENV: production
    package:
      include:
        - server.js